name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "setup pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "setup node"
        uses: "actions/setup-node@v4"
        with:
          node-version: 20

      - name: "Install"
        run: "pnpm install"

      - name: "MarkdownLint 检查"
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          fix: true
          globs: 'docs*/**/*.md'

      - name: "构建 测试"
        run: "pnpm run build"